version: '3'
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres      # שינוי חזרה ל-postgres
      POSTGRES_PASSWORD: 208664219
      POSTGRES_DB: world_war_2_db
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]  # שינוי ל-postgres
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build: .
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "5001:5001"
    environment:
      - DATABASE_URL=postgresql://postgres:208664219@db:5432/world_war_2_db  # שינוי ל-postgres

volumes:
  db_data: